### ISSUE TITLE
cannot install nvidia-tensorrt dependency

### ISSUE THREAD

**Issue by irgipaulius** [emrecanaltinsoy/keras2trt#1]
running command:
```
pip install nvidia-pyindex==1.0.9 \
&& pip install nvidia-tensorrt==8.4.2.4
```

response: 
```
ERROR: Could not find a version that satisfies the requirement nvidia-tensorrt==8.4.2.4 (from versions: 0.0.1.dev4, 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-tensorrt==8.4.2.4
```

system:
tried it on an M1 Macbook, and on a Windows machine with an Nvidia gpu.

also, based on the readme documentation, it's suggested that this module can be loaded straight from pip. But pip search shows no library named keras2trt: https://pypi.org/search/?q=keras2trt&o=

**Comment by emrecanaltinsoy** [comment]
@irgipaulius sorry for the inconvenience. I uploaded the package back to PyPI, now you should be able to install it via pip. 

The below command is tested on Linux and it works, however it does not seem to be working on Windows. I will look into this, thanks for pointing it out.
```
pip install nvidia-pyindex==1.0.9 \
&& pip install nvidia-tensorrt==8.4.2.4
```

**Comment by emrecanaltinsoy** [comment]
Please check [here ](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing)where it states,
> The zip file is the only option currently for Windows.

Zip installation guide: https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-zip
